name: "이슈 생성"
description: "Jira와 연동됩니다"
title: "[FEAT] "
body:
  - type: input
    id: parentKey
    attributes:
      label: "🎟️ 상위 작업 (Ticket Number)"
      placeholder: "GRT-00"
    validations:
      required: true

  - type: dropdown
    id: branchType
    attributes:
      label: "🌿 브랜치 유형"
      options:
        - feature
        - hotfix
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: "🌳 브랜치에 포함될 작업 내용"
      description: "영어로만 작성 (한글 X)"
      placeholder: "common_components"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📝 Description"
      value: |
        - 구현할 내용 1
        - 구현할 내용 2
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "✅ Todo"
      value: |
        - [ ] 구현할 내용 1
        - [ ] 구현할 내용 2
    validations:
      required: true
